(async()=>{try{
if(document.getElementById("mkcsvexporter"))return;
const P=new DOMParser(),get=async u=>fetch(u,{credentials:"same-origin"}).then(r=>{if(!r.ok)throw Error("HTTP "+r.status);return r.text()}),c=s=>String(s||"").replace(/\s+/g," ").trim(),coord=s=>(String(s).match(/(\d{1,3}\|\d{1,3})/)||[])[1],num=s=>Number(String(s||"").replace(/[^\d-]/g,""))||0;
const units=["spear","sword","axe","archer","spy","light","marcher","heavy","ram","catapult","knight","snob"];
const labels={spear:"Kopiníci",sword:"Šermíři",axe:"Sekery",archer:"Lučištníci",spy:"Špehové",light:"Lehká jízda",marcher:"Jízdní lučištníci",heavy:"Těžká jízda",ram:"Beranidla",catapult:"Katapulty",knight:"Paladin",snob:"Šlechtici"};
const box=document.createElement("div");box.id="mkcsvexporter";box.innerHTML=`<div style="position:fixed;inset:0;background:#0009;z-index:99998"></div><div style="position:fixed;top:4%;left:50%;transform:translateX(-50%);z-index:99999;width:min(680px,95vw);max-height:92vh;overflow:auto;background:#f4e4bc;border:3px solid #7d510f;border-radius:8px;padding:14px;font:14px Arial;color:#2b1b09"><div style="display:flex;justify-content:space-between"><b style="font-size:20px">Export vesnic a armády</b><button id=x>✕</button></div><div style="margin-top:8px;padding:8px;background:#fff7df;border:1px solid #9b6b22">Exportuje jednotky, které jsou <b>aktuálně doma</b>.</div><p><button id=a>Označit vše</button> <button id=n>Zrušit označení</button> <button id=r>Obnovit skupiny</button></p><select id=g multiple size=15 style="width:100%;min-height:320px"></select><div id=k style="margin-top:7px;font-weight:bold"></div><button id=e style="margin-top:12px;font-size:17px;font-weight:bold;padding:9px 16px">Exportovat vesnice + armádu</button><div id=m style="margin-top:10px;font-weight:bold"></div></div>`;document.body.append(box);
const $=s=>box.querySelector(s),msg=(t,err=false)=>{$("#m").textContent=t;$("#m").style.color=err?"#a00000":"#2b1b09"};$("#x").onclick=()=>box.remove();
const groups=new Map(),valid=n=>n&&!/^(vesnice|village|villages|skupina|skupiny|groups?|přehled vesnic|overview villages)$/i.test(n);
function add(doc){doc.querySelectorAll('a[href*="group="],select[name="group"] option,select[name="group_id"] option,#group_select option,option[data-group-id],[data-group-id],[data-group]').forEach(el=>{let raw=el.getAttribute("href")||el.value||"",id=(raw.match(/[?&]group=(\d+)/)||[])[1]||(String(raw).match(/^(\d+)$/)||[])[1]||el.dataset.groupId||el.dataset.group,n=c(el.textContent).replace(/^\[(.+)\]$/,"$1");if(id&&valid(n))groups.set(String(id),n)})}
async function loadGroups(){groups.clear();msg("Načítám skupiny…");for(const u of ["/game.php?screen=groups","/game.php?screen=overview_villages&mode=combined&group=0&page=-1","/game.php?screen=overview_villages&mode=combined"]){try{add(P.parseFromString(await get(u),"text/html"))}catch(_){}}try{let t=await fetch("/game.php?screen=groups&ajax=load_group_menu",{credentials:"same-origin",headers:{"TribalWars-Ajax":"1"}}).then(r=>r.text());try{let j=JSON.parse(t),walk=o=>{if(!o||typeof o!=="object")return;if(Array.isArray(o))return o.forEach(walk);let id=o.group_id??o.id??o.value,n=c(o.name??o.label??o.text);if(id!==undefined&&/^\d+$/.test(String(id))&&valid(n))groups.set(String(id),n);Object.values(o).forEach(walk)};walk(j)}catch(_){add(P.parseFromString(t,"text/html"))}}catch(_){}
$("#g").innerHTML=[...groups].sort((a,b)=>a[1].localeCompare(b[1],"cs")).map(([id,n])=>`<option value="${id}">${n}</option>`).join("");update();msg(`Načteno skupin: ${groups.size}.`)}
function update(){$("#k").textContent=`Označeno skupin: ${$("#g").selectedOptions.length} z ${$("#g").options.length}`}
$("#g").onchange=update;$("#a").onclick=()=>{[...$("#g").options].forEach(o=>o.selected=true);update()};$("#n").onclick=()=>{[...$("#g").options].forEach(o=>o.selected=false);update()};$("#r").onclick=loadGroups;
function cols(table){let out={};[...table.querySelectorAll("tr")].slice(0,4).forEach(tr=>[...tr.children].forEach((td,i)=>{let img=td.querySelector("img"),src=img?.src||"",u=td.dataset.unit||(src.match(/unit_([a-z]+)\./i)||[])[1]||(String(td.className).match(/unit-item-([a-z]+)/i)||[])[1];if(units.includes(u))out[u]=i}));return out}
function village(tr,uc){let co=coord(tr.textContent);if(!co)return null;let links=[...tr.querySelectorAll('a[href*="village="]')],a=links.find(x=>c(x.textContent).includes(co))||links[0];if(!a)return null;let id=((a.getAttribute("href")||"").match(/[?&]village=(\d+)/)||[])[1];if(!id)return null;let name=c(a.textContent).replace(new RegExp(`\\(?\\s*${co.replace("|","\\|")}\\s*\\)?`,"g"),"").replace(/^[\s\-–—:]+|[\s\-–—:]+$/g,"").trim(),cells=[...tr.children],us={};units.forEach(u=>us[u]=uc[u]!==undefined&&cells[uc[u]]?num(cells[uc[u]].textContent):0);let [x,y]=co.split("|").map(Number);return{id,name,coord:co,continent:`K${Math.floor(y/100)}${Math.floor(x/100)}`,units:us}}
async function groupArmy(id,name){let last;for(const u of [`/game.php?screen=overview_villages&mode=units&type=home&group=${id}&page=-1`,`/game.php?screen=overview_villages&mode=units&group=${id}&page=-1`]){try{let doc=P.parseFromString(await get(u),"text/html"),best=null,bc={};[...doc.querySelectorAll("table")].forEach(t=>{let x=cols(t);if(Object.keys(x).length>Object.keys(bc).length){best=t;bc=x}});if(!best||!Object.keys(bc).length)throw Error("Tabulka armády nebyla nalezena");let map=new Map();best.querySelectorAll("tr").forEach(tr=>{let v=village(tr,bc);if(v&&!map.has(v.id))map.set(v.id,{group:name,...v})});if(map.size)return{villages:[...map.values()],detected:Object.keys(bc)};throw Error("Nebyly nalezeny vesnice")}catch(e){last=e}}throw last}
const q=v=>`"${String(v??"").replace(/"/g,'""')}"`;
$("#e").onclick=async()=>{let sel=[...$("#g").selectedOptions].map(o=>({id:o.value,name:c(o.textContent)}));if(!sel.length)return msg("Označ alespoň jednu skupinu.",true);$("#e").disabled=true;try{let all=[],det=new Set();for(let i=0;i<sel.length;i++){msg(`Načítám armádu ${i+1}/${sel.length}: ${sel[i].name}…`);let r=await groupArmy(sel[i].id,sel[i].name);all.push(...r.villages);r.detected.forEach(u=>det.add(u))}let active=units.filter(u=>det.has(u)),rows=[["Skupina","Název vesnice","Souřadnice","Kontinent",...active.map(u=>labels[u])]];all.forEach(v=>rows.push([v.group,v.name,v.coord,v.continent,...active.map(u=>v.units[u]??0)]));let csv="\ufeff"+rows.map(r=>r.map(q).join(";")).join("\r\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8;"}),a=document.createElement("a"),d=new Date(),p=n=>String(n).padStart(2,"0");a.href=URL.createObjectURL(blob);a.download=`export_army_${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);msg(`Hotovo: exportováno ${all.length} vesnic. Stav armády: DOMA.`)}catch(e){msg("Chyba exportu armády: "+e.message,true)}finally{$("#e").disabled=false}};
await loadGroups()
}catch(e){alert("Chyba exportéru: "+e.message)}})();